// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSThemeColors
{
    internal sealed partial class Vsix
    {
        public const string Id = "6ad27930-f7a1-4888-a172-c6fa4440e7a0";
        public const string Name = "VS Theme Colors 2019";
        public const string Description = @"Makes it easy to browse all the brushes and select the right theme color for your Visual Studio extension UI.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
