// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSThemeColors
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSThemeColorsPackageString = "789c0c6f-9cd6-4086-9c42-8d951049a4d2";
        public static Guid guidVSThemeColorsPackage = new Guid(guidVSThemeColorsPackageString);

        public const string guidSwatchWindowString = "aeb5f170-736b-460e-9793-876b6bf60c1c";
        public static Guid guidSwatchWindow = new Guid(guidSwatchWindowString);

        public const string guidVSThemeColorsPackageCmdSetString = "ea3f240e-c9cb-49a4-b603-3a54d2f6fac6";
        public static Guid guidVSThemeColorsPackageCmdSet = new Guid(guidVSThemeColorsPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int OpenThemeWindowId = 0x0100;
    }
}